### ISSUE TITLE
Successfully installed bitsandbytes-0.41.1 BUT it isn't compiled for GPU it says.

### ISSUE THREAD

**Issue by DarkAlchy** [jllllll/bitsandbytes-windows-webui#15]
>python -m bitsandbytes

\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found

RTX 4090 here.

**Comment by jllllll** [comment]
Make sure that you don't have the CPU version of Pytorch installed. You can check with:
```
python -m torch.utils.collect_env
```
If you don't have the CPU version installed, then post the output of this command:
```
python -m bitsandbytes
```
Make sure to censor any sensitive information that might be displayed before posting.

**Comment by DarkAlchy** [comment]
Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: 3.9.1 (branches/release_39)
CMake version: version 3.27.4
Libc version: N/A

Python version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 531.79
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3501
DeviceID=CPU0
Family=107
L2CacheSize=3072
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3501
Name=AMD Ryzen 5 5600 6-Core Processor
ProcessorType=3
Revision=8450

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.6
[pip3] numpy==1.23.5
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-lightning==1.9.0
[pip3] torch==2.0.1+cu118
[pip3] torchmetrics==1.1.1
[pip3] torchvision==0.15.2+cu118
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.2.0         h6a75c08_49573    conda-forge
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.6           py310h4ed8f06_1
[conda] mkl_random                1.2.2           py310h4ed8f06_1
[conda] numpy                     1.25.2          py310h055cbcc_0
[conda] numpy-base                1.25.2          py310h65a83cf_0
[conda] pytorch                   2.0.1           cpu_py310hb0bdfb8_0
[conda] torchsde                  0.2.6                    pypi_0    pypi

---------------------

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++ PYTORCH CUDA PATHS ++++++++++++++++++++
F:\kohya_ss-win\venv\Lib\site-packages\torch\lib\c10_cuda.dll
F:\kohya_ss-win\venv\Lib\site-packages\torch\lib\cudart64_110.dll
F:\kohya_ss-win\venv\Lib\site-packages\torch\lib\torch_cuda.dll

+++++++++++++++++++ CUDA_PATH CUDA PATHS +++++++++++++++++++
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudart32_110.dll
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudart64_110.dll

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\kohya_ss-win\venv\lib\site-packages\bitsandbytes\__main__.py", line 121, in <module>
    generate_bug_report_information()
  File "F:\kohya_ss-win\venv\lib\site-packages\bitsandbytes\__main__.py", line 79, in generate_bug_report_information
    paths = find_file_recursive('/usr/local', '*cuda*' + SHARED_LIB_EXTENSION)
  File "F:\kohya_ss-win\venv\lib\site-packages\bitsandbytes\__main__.py", line 41, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file.')
RuntimeError: Something when wrong when trying to find file.

**Comment by jllllll** [comment]
Not sure why that error at the end is occurring. Python seems to think that the path `/usr/local/` exists, which shouldn't be happening given that is a Linux path.

There are 2 ways I can think of to get around this, though I'm not sure what the actual problem is.
- Use the `BNB_CUDA_VERSION` environment variable to force the correct CUDA version to load.
  - CMD: `set BNB_CUDA_VERSION=118`
  - Powershell: `$env:BNB_CUDA_VERSION = '118'`
- Install the CUDA runtime libs into the Conda environment.
  - `conda install -c nvidia/label/cuda-11.8.0 cuda-runtime`

**Comment by DarkAlchy** [comment]
I did the install, and everything installed fine.  I opened up the cli to activate the environment to do python -m bitsandbytes  and the exact same error.  Something is borked looking for stuff in a Linux directory.

**Comment by jllllll** [comment]
As you can see here: https://github.com/jllllll/bitsandbytes/blob/cmake_windows/bitsandbytes/__main__.py#L78
That code already has a check to prevent this issue, but the check is passing seemingly because Python believes that path exists.

It isn't actually relevant to the `compiled without GPU support` issue as that path is not directly accessed at all in the loading code: https://github.com/jllllll/bitsandbytes/blob/cmake_windows/bitsandbytes/cuda_setup/main.py#L258-L389

That Linux path bug is only occurring as part of the debug info function that is called when running `python -m bitsandbytes`.
The only real way to know if bitsandbytes is working or not is to actually try using it.
The debug info code from `python -m bitsandbytes` is somewhat isolated from the bulk of the bitsandbytes functionality.
Not sure why Tim made it that way.
It is entirely possible for `python -m bitsandbytes` to fail while an actual program utilizing bitsandbytes could work just fine.

**Comment by jllllll** [comment]
Here is some basic Python code for testing bitsandbytes with a model in a way that would be relevant to whether it works or not:
```py
from transformers import AutoModelForCausalLM,AutoConfig,AutoTokenizer,BitsAndBytesConfig
import torch
import torch.nn as nn
import os

model_path = r'G:\F\Projects\AI\text-generation-webui\one-click-installers-test\text-generation-webui\models\Neko-Institute-of-Science_LLaMA-7B-HF'
MAX_NEW_TOKENS = 200

checkpoint = os.path.realpath(model_path) if os.path.lexists(model_path) else model_path
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
config = AutoConfig.from_pretrained(checkpoint, trust_remote_code=False)
max_memory = {0: f'{int(torch.cuda.mem_get_info()[0]/1024**3)}GB', 'cpu': '99GiB'}
model = AutoModelForCausalLM.from_pretrained(
  checkpoint,
  low_cpu_mem_usage=True,
  device_map='auto',
  quantization_config=BitsAndBytesConfig(load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=False,),
  max_memory=max_memory)



prompt = 'Hello! How are you doing today?\n'

input_ids = tokenizer(prompt, return_tensors="pt").input_ids
generated_ids = model.generate(input_ids, max_length=MAX_NEW_TOKENS)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True))
```

**Comment by DarkAlchy** [comment]
Well, I have a program that was giving me that error and no matter what I did that error is preventing it from working.  I will try the above now, but as long as that error about the path exists the program I wish to use is dead.

**Comment by DarkAlchy** [comment]
E:\Downloads>python testbitsandbytes.py
Traceback (most recent call last):
  File "E:\Downloads\testbitsandbytes.py", line 1, in <module>
    from transformers import AutoModelForCausalLM,AutoConfig,AutoTokenizer,BitsAndBytesConfig
ImportError: cannot import name 'BitsAndBytesConfig' from 'transformers'

**Comment by jllllll** [comment]
That is possibly due to an outdated version of transformers.
I'm not sure what the problem is here. I've never used kohya_ss before, but others have used this with it successfully in the past.

---
Had another look at your `python -m torch.utils.collect_env` output and their is some indication of package conflicts between the pip packages and Conda packages.
Try replacing any Conda Pytorch packages with their pip equivalents:
```
conda remove pytorch* torchvision torchaudio
python -m pip install torch==2.0.1+cu118 torchvision torchaudio --upgrade --index-url https://download.pytorch.org/whl/cu118
```
One thing I've noticed with Pytorch's Conda packages is that they often do not install correctly and there isn't much we can do about it. Following their official installation instructions often ends up installing the CPU-only version.
This is indicated by this line in your Pytorch env info: `[conda] pytorch 2.0.1 cpu_py310hb0bdfb8_0`
These days I avoid installing Pytorch through Conda as much as possible.

**Comment by DarkAlchy** [comment]
Don't take the kohya_ss as what  I am trying to use I am only using its known good, and working, venv.  I already deleted the other program (d8's Dreambooth trainer) and will delete everything that doesn't work due to bitsandbytes.

Thanks for the help.
