### ISSUE TITLE
Lib is hardcoded to C:

### ISSUE THREAD

**Issue by inno-simon** [jllllll/bitsandbytes-windows-webui#3]
in cuda_setup/main.py

`CUDA_SHARED_LIB_NAME: str = "libcuda.so" if not IS_WINDOWS_PLATFORM else "C:\\Windows\\System32\\nvcuda.dll"`

Should probably use something like `f"{os.environ['windir']}\\System32\\nvcuda.dll"` so it works on all letters.

**Comment by jllllll** [comment]
I wasn't the one who coded that, but I can certainly change it! I've been meaning to re-order the runtime search paths anyway. It doesn't make sense to search PATH before searching CUDA_PATH since PATH can potentially contain multiple runtimes and none of them have to be relevant to the current task.
